--270812
--CREATE TABLE IF NOT EXISTS tag SELECT COUNT(DISTINCT tag) FROM features_tags;

DROP TABLE IF EXISTS tags;
CREATE TABLE IF NOT EXISTS tags  ENGINE=MYISAM DEFAULT CHARSET=UTF8MB4  SELECT DISTINCT tag FROM
    features_tags;

